#include <map>
#include <string>
#include "townsdef.h"

std::map <unsigned int,std::string> FMTownsIOMap(void)
{
	std::map <unsigned int,std::string> ioMap;
	ioMap[TOWNSIO_PIC_PRIMARY_ICW1]="PIC_PRIMARY_ICW1";
	ioMap[TOWNSIO_PIC_PRIMARY_ICW2_3_4_OCW]="PIC_PRIMARY_ICW2_3_4_OCW";
	ioMap[TOWNSIO_PIC_SECONDARY_ICW1]="PIC_SECONDARY_ICW1";
	ioMap[TOWNSIO_PIC_SECONDARY_ICW2_3_4_OCW]="PIC_SECONDARY_ICW2_3_4_OCW";
	ioMap[TOWNSIO_RESET_REASON]="RESET_REASON";
	ioMap[TOWNSIO_FREERUN_TIMER     ]="FREERUN_TIMER     ";
	ioMap[TOWNSIO_FREERUN_TIMER_LOW ]="FREERUN_TIMER_LOW ";
	ioMap[TOWNSIO_FREERUN_TIMER_HIGH]="FREERUN_TIMER_HIGH";
	ioMap[TOWNSIO_MACHINE_ID_LOW]="MACHINE_ID_LOW";
	ioMap[TOWNSIO_MACHINE_ID_HIGH]="MACHINE_ID_HIGH";
	ioMap[TOWNSIO_DMAC_INITIALIZE]="DMAC_INITIALIZE";
	ioMap[TOWNSIO_DMAC_CHANNEL]="DMAC_CHANNEL";
	ioMap[TOWNSIO_DMAC_COUNT_LOW]="DMAC_COUNT_LOW";
	ioMap[TOWNSIO_DMAC_COUNT_HIGH]="DMAC_COUNT_HIGH";
	ioMap[TOWNSIO_DMAC_ADDRESS_LOWEST]="DMAC_ADDRESS_LOWEST";
	ioMap[TOWNSIO_DMAC_ADDRESS_MIDLOW]="DMAC_ADDRESS_MIDLOW";
	ioMap[TOWNSIO_DMAC_ADDRESS_MIDHIGH]="DMAC_ADDRESS_MIDHIGH";
	ioMap[TOWNSIO_DMAC_ADDRESS_HIGHEST]="DMAC_ADDRESS_HIGHEST";
	ioMap[TOWNSIO_DMAC_DEVICE_CONTROL_LOW]="DMAC_DEVICE_CONTROL_LOW";
	ioMap[TOWNSIO_DMAC_DEVICE_CONTROL_HIGH]="DMAC_DEVICE_CONTROL_HIGH";
	ioMap[TOWNSIO_DMAC_MODE_CONTROL]="DMAC_MODE_CONTROL";
	ioMap[TOWNSIO_DMAC_STATUS]="DMAC_STATUS";
	ioMap[TOWNSIO_DMAC_TEMPORARY_REG_LOW]="DMAC_TEMPORARY_REG_LOW";
	ioMap[TOWNSIO_DMAC_TEMPORARY_REG_HIGH]="DMAC_TEMPORARY_REG_HIGH";
	ioMap[TOWNSIO_DMAC_REQUEST]="DMAC_REQUEST";
	ioMap[TOWNSIO_DMAC_MASK]="DMAC_MASK";
	ioMap[TOWNSIO_FDC_STATUS_COMMAND]="FDC_STATUS_COMMAND";
	ioMap[TOWNSIO_FDC_TRACK]="FDC_TRACK";
	ioMap[TOWNSIO_FDC_SECTOR]="FDC_SECTOR";
	ioMap[TOWNSIO_FDC_DATA]="FDC_DATA";
	ioMap[TOWNSIO_FDC_DRIVE_STATUS_CONTROL]="FDC_DRIVE_STATUS_CONTROL";
	ioMap[TOWNSIO_FDC_DRIVE_SELECT]="FDC_DRIVE_SELECT";
	ioMap[TOWNSIO_FDC_DRIVE_SWITCH]="FDC_DRIVE_SWITCH";
	ioMap[TOWNSIO_FMR_RESOLUTION]="FMR_RESOLUTION";
	ioMap[TOWNSIO_FMR_VRAM_OR_MAINRAM]="FMR_VRAM_OR_MAINRAM";
	ioMap[TOWNSIO_VRAMACCESSCTRL_ADDR]="VRAMACCESSCTRL_ADDR";
	ioMap[TOWNSIO_VRAMACCESSCTRL_DATA_LOW]="VRAMACCESSCTRL_DATA_LOW";
	ioMap[TOWNSIO_VRAMACCESSCTRL_DATA_HIGH]="VRAMACCESSCTRL_DATA_HIGH";
	ioMap[TOWNSIO_MX_HIRES]="MX_HIRES";
	ioMap[TOWNSIO_MX_VRAMSIZE]="MX_VRAMSIZE";
	ioMap[TOWNSIO_MX_IMGOUT_ADDR_LOW]="MX_IMGOUT_ADDR_LOW";
	ioMap[TOWNSIO_MX_IMGOUT_ADDR_HIGH]="MX_IMGOUT_ADDR_HIGH";
	ioMap[TOWNSIO_MX_IMGOUT_ADDR_D0]="MX_IMGOUT_ADDR_D0";
	ioMap[TOWNSIO_MX_IMGOUT_ADDR_D1]="MX_IMGOUT_ADDR_D1";
	ioMap[TOWNSIO_MX_IMGOUT_ADDR_D2]="MX_IMGOUT_ADDR_D2";
	ioMap[TOWNSIO_MX_IMGOUT_ADDR_D3]="MX_IMGOUT_ADDR_D3";
	ioMap[TOWNSIO_CDROM_MASTER_CTRL_STATUS]="CDROM_MASTER_CTRL_STATUS";
	ioMap[TOWNSIO_CDROM_COMMAND_STATUS]="CDROM_COMMAND_STATUS";
	ioMap[TOWNSIO_CDROM_PARAMETER_DATA]="CDROM_PARAMETER_DATA";
	ioMap[TOWNSIO_CDROM_TRANSFER_CTRL]="CDROM_TRANSFER_CTRL";
	ioMap[TOWNSIO_CDROM_SUBCODE_STATUS]="CDROM_SUBCODE_STATUS";
	ioMap[TOWNSIO_CDROM_SUBCODE_DATA]="CDROM_SUBCODE_DATA";
	ioMap[TOWNSIO_SYSROM_DICROM]="SYSROM_DICROM";
	ioMap[TOWNSIO_MEMSIZE]="MEMSIZE";
	ioMap[TOWNSIO_KEYBOARD_DATA]="KEYBOARD_DATA";
	ioMap[TOWNSIO_KEYBOARD_STATUS_CMD]="KEYBOARD_STATUS_CMD";
	ioMap[TOWNSIO_KEYBOARD_IRQ]="KEYBOARD_IRQ";
	ioMap[TOWNSIO_FMR_DIGITALPALETTE0]="FMR_DIGITALPALETTE0";
	ioMap[TOWNSIO_FMR_DIGITALPALETTE1]="FMR_DIGITALPALETTE1";
	ioMap[TOWNSIO_FMR_DIGITALPALETTE2]="FMR_DIGITALPALETTE2";
	ioMap[TOWNSIO_FMR_DIGITALPALETTE3]="FMR_DIGITALPALETTE3";
	ioMap[TOWNSIO_FMR_DIGITALPALETTE4]="FMR_DIGITALPALETTE4";
	ioMap[TOWNSIO_FMR_DIGITALPALETTE5]="FMR_DIGITALPALETTE5";
	ioMap[TOWNSIO_FMR_DIGITALPALETTE6]="FMR_DIGITALPALETTE6";
	ioMap[TOWNSIO_FMR_DIGITALPALETTE7]="FMR_DIGITALPALETTE7";
	ioMap[TOWNSIO_FMR_VRAMMASK]="FMR_VRAMMASK";
	ioMap[TOWNSIO_FMR_VRAMDISPLAYMODE]="FMR_VRAMDISPLAYMODE";
	ioMap[TOWNSIO_FMR_VRAMPAGESEL]="FMR_VRAMPAGESEL";
	return ioMap;
}
