#include <stdio.h>
#include "io.h"

enum
{
	TOWNSIO_VNDRV_APICHECK=       0x2F10,
	TOWNSIO_VNDRV_ENABLE=         0x2F12,
	TOWNSIO_VNDRV_COMMAND=        0x2F14,
	TOWNSIO_VNDRV_AUXCOMMAND=     0x2F18,

	TOWNS_VNDRV_AUXCMD_DEBUGBREAK=0x00,
	TOWNS_VNDRV_AUXCMD_PRINTCSTR= 0x09,
	TOWNS_VNDRV_AUXCMD_MEMDUMP=   0x0A,

	ENABLE_CODE=1,
	DISABLE_CODE=0,
};

int main(void)
{
	IOWriteWord(TOWNSIO_VNDRV_ENABLE,ENABLE_CODE);
	IOWriteByte(TOWNSIO_VNDRV_AUXCOMMAND,TOWNS_VNDRV_AUXCMD_DEBUGBREAK);
	return 0;
}
